//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomTime.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int XPos {
            get {
                return ((int)(this["XPos"]));
            }
            set {
                this["XPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int YPos {
            get {
                return ((int)(this["YPos"]));
            }
            set {
                this["YPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int XOffset {
            get {
                return ((int)(this["XOffset"]));
            }
            set {
                this["XOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int YOffset {
            get {
                return ((int)(this["YOffset"]));
            }
            set {
                this["YOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600000")]
        public int BarTime {
            get {
                return ((int)(this["BarTime"]));
            }
            set {
                this["BarTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public int BarWidth {
            get {
                return ((int)(this["BarWidth"]));
            }
            set {
                this["BarWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BarSeperators {
            get {
                return ((int)(this["BarSeperators"]));
            }
            set {
                this["BarSeperators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys HotkeyStartKeycode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HotkeyStartKeycode"]));
            }
            set {
                this["HotkeyStartKeycode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeyStartShift {
            get {
                return ((bool)(this["HotkeyStartShift"]));
            }
            set {
                this["HotkeyStartShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeyStartControl {
            get {
                return ((bool)(this["HotkeyStartControl"]));
            }
            set {
                this["HotkeyStartControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotkeyStartAlt {
            get {
                return ((bool)(this["HotkeyStartAlt"]));
            }
            set {
                this["HotkeyStartAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotkeyStartWin {
            get {
                return ((bool)(this["HotkeyStartWin"]));
            }
            set {
                this["HotkeyStartWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public global::System.Windows.Forms.Keys HotkeyPauseKeycode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HotkeyPauseKeycode"]));
            }
            set {
                this["HotkeyPauseKeycode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeyPauseShift {
            get {
                return ((bool)(this["HotkeyPauseShift"]));
            }
            set {
                this["HotkeyPauseShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotkeyPauseAlt {
            get {
                return ((bool)(this["HotkeyPauseAlt"]));
            }
            set {
                this["HotkeyPauseAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotkeyPauseWin {
            get {
                return ((bool)(this["HotkeyPauseWin"]));
            }
            set {
                this["HotkeyPauseWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeyPauseControl {
            get {
                return ((bool)(this["HotkeyPauseControl"]));
            }
            set {
                this["HotkeyPauseControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public global::System.Windows.Forms.Keys HotkeyHideKeycode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HotkeyHideKeycode"]));
            }
            set {
                this["HotkeyHideKeycode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeyHideControl {
            get {
                return ((bool)(this["HotkeyHideControl"]));
            }
            set {
                this["HotkeyHideControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotkeyHideAlt {
            get {
                return ((bool)(this["HotkeyHideAlt"]));
            }
            set {
                this["HotkeyHideAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeyHideShift {
            get {
                return ((bool)(this["HotkeyHideShift"]));
            }
            set {
                this["HotkeyHideShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HotkeyHideWin {
            get {
                return ((bool)(this["HotkeyHideWin"]));
            }
            set {
                this["HotkeyHideWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color BarColor {
            get {
                return ((global::System.Drawing.Color)(this["BarColor"]));
            }
            set {
                this["BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int BarHeight {
            get {
                return ((int)(this["BarHeight"]));
            }
            set {
                this["BarHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color BlinkingColor {
            get {
                return ((global::System.Drawing.Color)(this["BlinkingColor"]));
            }
            set {
                this["BlinkingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Blinking {
            get {
                return ((bool)(this["Blinking"]));
            }
            set {
                this["Blinking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int TimeToBlink {
            get {
                return ((int)(this["TimeToBlink"]));
            }
            set {
                this["TimeToBlink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color CountBackColor {
            get {
                return ((global::System.Drawing.Color)(this["CountBackColor"]));
            }
            set {
                this["CountBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CountBack {
            get {
                return ((bool)(this["CountBack"]));
            }
            set {
                this["CountBack"] = value;
            }
        }
    }
}
